version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: prisma # Edit this data
      POSTGRES_USER: prisma # Edit this data
      POSTGRES_PASSWORD: prisma # Edit this data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: